# Nome dell'applicazione
spring.application.name=ExpenseTracker

# Connessione al Database (Quello che abbiamo messo nel docker-compose)
spring.datasource.url=jdbc:postgresql://localhost:5432/expensedb
spring.datasource.username=devuser
spring.datasource.password=devpassword
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurazione JPA (Hibernate)
# ddl-auto=update significa: "Se cambio una classe Java, aggiorna la tabella SQL da solo"
spring.jpa.hibernate.ddl-auto=update
# show-sql=true significa: "Fammi vedere nel terminale le query SQL che scrivi di nascosto"
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true